name: PR

on:
  pull_request:
    branches: [main]

jobs:
  checks:
    uses: linked-cm/.github/.github/workflows/pr.yml@v1
    permissions:
      contents: read
      pull-requests: write
    with:
      require-tests: true
      run-e2e: false
